/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#	include <config.h>
#endif

#include <gtk/gtk.h>

#include "Mainwindow.h"
#include "Init.h"
#include "Funs.h"

struct clist_struct clist;
static int sta = 0;

void callback_icon(GtkStatusIcon *status_icon,gpointer data)
{
	GtkWidget *main = (GtkWidget *)data;
	if (sta == 0) {
		gtk_widget_hide(main);
		sta = 1;
	} else {
		gtk_widget_show (main);
		sta = 0;
	}
}


int main (int argc, char *argv[])
{
	GdkPixbuf *panel_icon_pixbuf;
	GtkWidget *main_windown;
	GtkStatusIcon* icon;

#ifdef ENABLE_NLS
	bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
#endif

	gtk_set_locale ();
	gtk_init (&argc, &argv);
	
	add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
	add_pixmap_directory ("../pixmaps");
	add_pixmap_directory("./pixmaps");
	/*
	 * The following code was added by Glade to create one of each component
	 * (except popup menus), just so that you see something after building
	 * the project. Delete any components that you don't want shown initially.
	 */
	
	init_global_clist(&clist);
	
	main_windown = create_main_windown (&clist);
	panel_icon_pixbuf = create_pixbuf ("zhwen.png");
	icon = gtk_status_icon_new_from_pixbuf (panel_icon_pixbuf);
	gtk_status_icon_set_tooltip(icon,"Xnotebook");
	g_signal_connect((gpointer)icon, "activate", G_CALLBACK(callback_icon), main_windown);
	
	gtk_widget_show (main_windown);
	
	show_folders(&clist);
	show_rss(&clist);
	gtk_main ();
	return 0;
}

