/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#	include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "Menubar.h"
#include "Callbacks.h"
#include "Mainwindow.h"

GtkWidget*
create_main_windown (struct clist_struct *clist)
{
	GdkPixbuf *window_main_icon_pixbuf;
	GtkWidget *main_windown;
	GtkWidget *vbox_bottom;
	GtkWidget *vbox_head;
	/*---------menubar-----------*/
	GtkWidget *menubar;  
	/*---------toolebar-------*/
	GtkWidget *toolbar;
	/*---------edit-----------*/
	GtkWidget *hpaned;
	  
	GtkTooltips *tooltips;
	GtkAccelGroup *accel_group;

	accel_group = gtk_accel_group_new ();

	main_windown = gtk_window_new (GTK_WINDOW_TOPLEVEL);
	gtk_widget_set_size_request (main_windown, 900, 700);
	gtk_window_set_position (GTK_WINDOW (main_windown), GTK_WIN_POS_CENTER);
	gtk_window_set_title (GTK_WINDOW (main_windown), _("Zhwen-Xnotebook"));
	window_main_icon_pixbuf = create_pixbuf ("zhwen.png");
	if (window_main_icon_pixbuf)
	{
	gtk_window_set_icon (GTK_WINDOW (main_windown), window_main_icon_pixbuf);
	gdk_pixbuf_unref (window_main_icon_pixbuf);
	}

	vbox_bottom = gtk_vbox_new (FALSE, 0);
	gtk_widget_show (vbox_bottom);
	gtk_container_add (GTK_CONTAINER (main_windown), vbox_bottom);
	  
	vbox_head = gtk_vbox_new (FALSE, 0);
	gtk_widget_show (vbox_head);
	gtk_box_pack_start (GTK_BOX (vbox_bottom), vbox_head, FALSE, TRUE, 0);

	menubar=(GtkWidget *)create_menubar(main_windown, vbox_head, \
										tooltips, accel_group);
	toolbar=(GtkWidget *)create_toolbar(main_windown, vbox_head, \
										tooltips, accel_group, clist);

	hpaned=(GtkWidget *)create_mainbody(main_windown, vbox_bottom, \
										tooltips, accel_group, clist);
	
	g_signal_connect ((gpointer) main_windown, "delete_event",
	                  G_CALLBACK (on_main_windown_delete_event),
	                  NULL);

	/* Store pointers to all widgets, for use by lookup_widget(). */
	GLADE_HOOKUP_OBJECT_NO_REF (main_windown, main_windown, "main_windown");
	GLADE_HOOKUP_OBJECT (main_windown, vbox_bottom, "vbox_bottom");
	GLADE_HOOKUP_OBJECT (main_windown, vbox_head, "vbox_head");
	GLADE_HOOKUP_OBJECT (main_windown, menubar, "menubar");
	GLADE_HOOKUP_OBJECT (main_windown, toolbar, "toolbar");  
	GLADE_HOOKUP_OBJECT (main_windown, hpaned, "hpaned");  

	gtk_window_add_accel_group (GTK_WINDOW (main_windown), accel_group);
		
	return main_windown;
}

