/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "calendar.h"

gboolean
on_xcalendar_windown_delete_event (GtkWidget *widget, GdkEvent *event, 
									gpointer user_data)
{
	struct add_event_obj *obj = (struct add_event_obj *)user_data;
	
	obj->event_box = NULL;
	printf("bey world;\n");

	return FALSE;
}
void
create_xcalendar (GtkButton *button, struct add_event_obj *obj)
{
	GtkWidget *xcal_window;
	GtkWidget *dialog_vbox; 
	GtkWidget *xcal_vbox;
	GtkWidget *xcalendar;

	GtkWidget *xcal_body;
	GtkWidget *xcal_check;
	GtkTooltips *tooltip;

	GtkWidget *xcal_foot;
	GtkWidget *foot_label;
	GtkWidget *xbut_add;
	GtkWidget *ximg_add;
	
	CursorOffset* icon_pos;

	xcal_window = gtk_dialog_new_with_buttons("Xcalendar", 
		GTK_WINDOW(obj->main_window), GTK_DIALOG_DESTROY_WITH_PARENT,NULL);
	gtk_window_set_type_hint (GTK_WINDOW (xcal_window), GDK_WINDOW_TYPE_HINT_DIALOG);
	gtk_window_set_position (GTK_WINDOW (xcal_window), GTK_WIN_POS_MOUSE);
	gtk_widget_set_size_request (xcal_window, 220, -1);
	gtk_window_set_resizable (GTK_WINDOW (xcal_window), FALSE);
	gtk_window_set_destroy_with_parent (GTK_WINDOW (xcal_window), TRUE);
	gtk_window_set_modal (GTK_WINDOW (xcal_window), TRUE);
	//gtk_window_set_decorated(xcal_window, FALSE);
	gtk_widget_show(xcal_window);
	
	dialog_vbox = GTK_DIALOG (xcal_window)->vbox;
	gtk_widget_show (dialog_vbox);
	
	xcal_vbox = gtk_vbox_new(FALSE,0);
	gtk_widget_show(xcal_vbox);
	gtk_container_add(GTK_CONTAINER(dialog_vbox), xcal_vbox);
	
	xcalendar = gtk_calendar_new ();
	gtk_widget_show (xcalendar);
	gtk_box_pack_start (GTK_BOX (xcal_vbox), xcalendar, FALSE, TRUE, 0);
	gtk_calendar_display_options (GTK_CALENDAR (xcalendar),
				GTK_CALENDAR_SHOW_HEADING
				| GTK_CALENDAR_SHOW_DAY_NAMES
				| GTK_CALENDAR_SHOW_WEEK_NUMBERS);

/****************************************************************************************************/
	xcal_body = gtk_vbox_new(FALSE,0);
	gtk_widget_show (xcal_body);
	gtk_box_pack_start (GTK_BOX (xcal_vbox), xcal_body, TRUE, TRUE, 0);
	
	xcal_check = gtk_check_button_new_with_mnemonic (_("This a test for event!!!"));
	gtk_widget_show (xcal_check);
	gtk_box_pack_start (GTK_BOX (xcal_body), xcal_check, FALSE, FALSE, 0);

	tooltip = gtk_tooltips_new();
	gtk_tooltips_set_tip((GtkTooltips *)tooltip, xcal_check, "This a test for xevent!!!", NULL);

/****************************************************************************************************/
	xcal_foot = gtk_hbox_new(FALSE,0);
	gtk_widget_show (xcal_foot);
	gtk_box_pack_start (GTK_BOX (xcal_vbox), xcal_foot, FALSE, FALSE, 0);

	foot_label = gtk_label_new (_("state......"));
	gtk_widget_show (foot_label);
	gtk_box_pack_start (GTK_BOX (xcal_foot), foot_label, FALSE, FALSE, 0);
	gtk_widget_set_size_request (foot_label, 180, -1);
	gtk_label_set_line_wrap (GTK_LABEL (foot_label), TRUE);

	xbut_add = gtk_button_new ();
	gtk_widget_show (xbut_add);
	gtk_box_pack_start (GTK_BOX (xcal_foot), xbut_add, FALSE, FALSE, 0);
	gtk_button_set_relief (GTK_BUTTON (xbut_add), GTK_RELIEF_NONE);
	ximg_add = create_pixmap("add.png");
	gtk_widget_show (ximg_add);
	gtk_container_add (GTK_CONTAINER (xbut_add), ximg_add);
/****************************************************************************************************/
	obj->event_box = xcal_body;
	obj->xcalendar = xcalendar;
	gtk_signal_connect(GTK_OBJECT(xcalendar), "day_selected",
				G_CALLBACK(xcalendar_event), (struct add_event_obj *)obj);
	g_signal_connect(GTK_OBJECT(xbut_add), "clicked",
				G_CALLBACK(add_event), (struct add_event_obj *)obj);
	xcalendar_event(xcalendar, (struct add_event_obj *)obj);
/****************************************************************************************************/
	g_signal_connect ((gpointer) xcal_window, "delete_event",
				  G_CALLBACK (on_xcalendar_windown_delete_event),
				  (struct add_event_obj *)obj);	
}
