/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "main_window.h"
#include "calendar.h"
#include "event.h"
#include "setup.h"
#include "support.h"

struct add_event_obj obj;
struct xevent hevent;
struct top_show_event ts_event;

GtkWidget *create_main_window(void)
{
	GtkWidget *xcalendar;
	GtkWidget *main_body;

	GtkWidget *top_hbox;
	GtkWidget *xtime;
	GtkWidget *xbut_hbox;
	GtkWidget *ximg_ring;
	GtkWidget *xtitle;
	
	GtkWidget *xtoolbar;
	GtkWidget *xbut_xcal;
	GtkWidget *ximg_xcal;
	GtkWidget *xbut_event;
	GtkWidget *ximg_event;
	GtkWidget *xbut_add;
	GtkWidget *ximg_add;
	GtkWidget *xbut_setup;
	GtkWidget *ximg_setup;	
	GtkWidget *xbut_exit;
	GtkWidget *ximg_exit;

	GdkPixbuf *pixbuf = NULL;
	GdkPixmap *pixmap = NULL;
	CursorOffset* icon_pos;

	PangoFontDescription *fontdesc_title_time; 
	GdkPixbuf *xcal_icon_pixbuf;

	xcalendar = gtk_window_new(GTK_WINDOW_TOPLEVEL);
	gtk_window_set_default_size(GTK_WINDOW(xcalendar), 220, -1);
	gtk_window_set_position (GTK_WINDOW (xcalendar), GTK_WIN_POS_CENTER);
	//gtk_window_set_resizable(GTK_WINDOW(xcalendar),FALSE);
	//gtk_container_set_border_width (GTK_CONTAINER (xcalendar), 5);
	gtk_window_set_decorated(GTK_WINDOW (xcalendar), FALSE);

	gtk_widget_set_events (xcalendar,
	    gtk_widget_get_events (xcalendar) |
	    GDK_BUTTON_MOTION_MASK |
	    GDK_POINTER_MOTION_HINT_MASK |
	    GDK_BUTTON_PRESS_MASK);
	
	gtk_widget_realize (xcalendar);
	obj.main_window = xcalendar;
	
	xcal_icon_pixbuf = create_pixbuf ("logo.png");
	if (xcal_icon_pixbuf)
	{
		gtk_window_set_icon (GTK_WINDOW (xcalendar), xcal_icon_pixbuf);
		gdk_pixbuf_unref (xcal_icon_pixbuf);
	}

	main_body = gtk_vbox_new(FALSE,0);
	gtk_widget_show(main_body);
	gtk_container_add(GTK_CONTAINER(xcalendar), main_body);
/************************************************************************************************/

	top_hbox = gtk_hbox_new(FALSE,0);
	gtk_widget_show(top_hbox);
	gtk_box_pack_start (GTK_BOX (main_body), top_hbox, FALSE, FALSE, 0);

 	xtime = gtk_label_new_with_mnemonic (_("<span foreground='white'>Start......</span>"));
	gtk_widget_show (xtime);
	gtk_box_pack_start (GTK_BOX (top_hbox), xtime, FALSE, FALSE, 0);
	gtk_label_set_use_markup (GTK_LABEL (xtime), TRUE);

	fontdesc_title_time= pango_font_description_from_string("FreeSans Bold 20"); 
	gtk_widget_modify_font(xtime, fontdesc_title_time); 
	pango_font_description_free(fontdesc_title_time); 

	ximg_ring = create_pixmap("ring.png");
	gtk_widget_show (ximg_ring);
	gtk_box_pack_start (GTK_BOX (top_hbox), ximg_ring, FALSE, FALSE, 0);

	xtitle = gtk_label_new_with_mnemonic (_(" Today Events!!!"));
	gtk_widget_show (xtitle);
	gtk_box_pack_start (GTK_BOX (top_hbox), xtitle, FALSE, FALSE, 0);
	gtk_label_set_use_markup (GTK_LABEL (xtitle), TRUE);

	xtoolbar =  gtk_hbox_new(FALSE,0);
	gtk_widget_show(xtoolbar);
	gtk_box_pack_start (GTK_BOX (main_body), xtoolbar, TRUE, FALSE, 0);

	xbut_xcal = gtk_button_new ();
	gtk_widget_show (xbut_xcal);
	gtk_box_pack_start (GTK_BOX (xtoolbar), xbut_xcal, FALSE, FALSE, 0);
	gtk_widget_set_size_request (xbut_xcal, 50, 50);
	gtk_button_set_relief (GTK_BUTTON (xbut_xcal), GTK_RELIEF_NONE);
	ximg_xcal = create_pixmap("xcal1.png");
	gtk_widget_show (ximg_xcal);
	gtk_container_add (GTK_CONTAINER (xbut_xcal), ximg_xcal);
	
	xbut_event = gtk_button_new ();
	gtk_widget_show (xbut_event);
	gtk_box_pack_start (GTK_BOX (xtoolbar), xbut_event, FALSE, FALSE, 0);
	gtk_widget_set_size_request (xbut_event, 50, 50);
	gtk_button_set_relief (GTK_BUTTON (xbut_event), GTK_RELIEF_NONE);
	ximg_event = create_pixmap("event1.png");
	gtk_widget_show (ximg_event);
	gtk_container_add (GTK_CONTAINER (xbut_event), ximg_event);
	
	xbut_add = gtk_button_new ();
	gtk_widget_show (xbut_add);
	gtk_box_pack_start (GTK_BOX (xtoolbar), xbut_add, FALSE, FALSE, 0);
	gtk_widget_set_size_request (xbut_add, 50, 50);
	gtk_button_set_relief (GTK_BUTTON (xbut_add), GTK_RELIEF_NONE);
	ximg_add = create_pixmap("new1.png");
	gtk_widget_show (ximg_add);
	gtk_container_add (GTK_CONTAINER (xbut_add), ximg_add);
	
	xbut_setup = gtk_button_new ();
	gtk_widget_show (xbut_setup);
	gtk_box_pack_start (GTK_BOX (xtoolbar), xbut_setup, FALSE, FALSE, 0);
	gtk_widget_set_size_request (xbut_setup, 50, 50);
	gtk_button_set_relief (GTK_BUTTON (xbut_setup), GTK_RELIEF_NONE);
	ximg_setup = create_pixmap("setup1.png");
	gtk_widget_show (ximg_setup);
	gtk_container_add (GTK_CONTAINER (xbut_setup), ximg_setup);
	
	xbut_exit = gtk_button_new ();
	gtk_widget_show (xbut_exit);
	gtk_box_pack_start (GTK_BOX (xtoolbar), xbut_exit, FALSE, FALSE, 0);
	gtk_widget_set_size_request (xbut_exit, 50, 50);
	gtk_button_set_relief (GTK_BUTTON (xbut_exit), GTK_RELIEF_NONE);
	ximg_exit = create_pixmap("exit1.png");
	gtk_widget_show (ximg_exit);
	gtk_container_add (GTK_CONTAINER (xbut_exit), ximg_exit);	
/*************************************************************************************************/
	g_signal_connect (xcalendar, "button_press_event",
		    G_CALLBACK (shape_pressed), (gpointer *)xcalendar);
	g_signal_connect (xcalendar, "motion_notify_event",
		    G_CALLBACK (shape_motion), NULL);
	icon_pos = g_new (CursorOffset, 1);
	g_object_set_data (G_OBJECT (xcalendar), "cursor_offset", icon_pos);

	g_signal_connect(G_OBJECT(xbut_xcal), "enter_notify_event", 
			GTK_SIGNAL_FUNC(mouse_event_handle), "c");
	g_signal_connect(G_OBJECT(xbut_xcal), "leave_notify_event", 
			GTK_SIGNAL_FUNC(mouse_event_handle), "c");
	g_signal_connect((gpointer) xbut_xcal, "clicked",
			 G_CALLBACK(create_xcalendar), &obj);
			 
	g_signal_connect(G_OBJECT(xbut_event), "enter_notify_event", 
			GTK_SIGNAL_FUNC(mouse_event_handle), "e");
	g_signal_connect(G_OBJECT(xbut_event), "leave_notify_event", 
			GTK_SIGNAL_FUNC(mouse_event_handle), "e");
	g_signal_connect((gpointer) xbut_event, "clicked",
			 G_CALLBACK(create_event), &obj);
			 		
	g_signal_connect(G_OBJECT(xbut_add), "enter_notify_event", 
			GTK_SIGNAL_FUNC(mouse_event_handle), "n");
	g_signal_connect(G_OBJECT(xbut_add), "leave_notify_event", 
			GTK_SIGNAL_FUNC(mouse_event_handle), "n");
	g_signal_connect((gpointer) xbut_add, "clicked",
			 G_CALLBACK(add_event), &obj);
			 
	g_signal_connect(G_OBJECT(xbut_setup), "enter_notify_event", 
			GTK_SIGNAL_FUNC(mouse_event_handle), "s");
	g_signal_connect(G_OBJECT(xbut_setup), "leave_notify_event", 
			GTK_SIGNAL_FUNC(mouse_event_handle), "s");
									
	g_signal_connect((gpointer) xbut_exit, "clicked",
			 G_CALLBACK(on_main_delete_event), (gpointer *)&ts_event);
	g_signal_connect(G_OBJECT(xbut_exit), "enter_notify_event", 
			GTK_SIGNAL_FUNC(mouse_event_handle), "x");
	g_signal_connect(G_OBJECT(xbut_exit), "leave_notify_event", 
			GTK_SIGNAL_FUNC(mouse_event_handle), "x");
			 
	hevent.fin = -1;
	hevent.time = 0;
	sprintf(hevent.event, "Today is a Free day!!");
	hevent.next = NULL;
	ts_event.xtime = xtime;
	ts_event.xtitle = xtitle;
	ts_event.hevent = &hevent;
	obj.hevent = &hevent;
	
	char xdate[16];
	struct xevent *tmp = NULL;
	get_date_today(xdate);
	hevent.next = get_date_event(xdate, &hevent.time);
/*	tmp = hevent.next;
	if(tmp){
		do{
		printf("tmp->event:%s\n",tmp->event);
		}while(tmp = tmp->next);
	}
*/
	if (hevent.time > 0)
		snprintf(hevent.event, 22, "Today %d tasks to do!", hevent.time);
	
	gtk_timeout_add(10000, (GtkFunction)update_clock, (gpointer *)&ts_event);
	update_clock((gpointer *)&ts_event);
	return xcalendar;
}
