/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "setup.h"
#include "support.h"

GtkWidget *create_setup(void)
{
	GtkWidget *setup_vbox;
	
	setup_vbox = gtk_vbox_new(FALSE,0);

	return setup_vbox;
}
